name: Deployment to AWS EC2

on:
  push:
    branches:
      - development

jobs:
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/development'
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          cd /home/ubuntu/www/surrat_backend
          git checkout development
          git pull origin development
          
          # Ensure the pull was successful
          if [ $? -ne 0 ]; then
            echo "Git pull failed! Exiting..."
            exit 1
          fi
          
          # Build and deploy containers
          sudo docker-compose up --build -d

          # Run migrations
          docker-compose exec surrat_backend bash -c "python manage.py makemigrations && python manage.py migrate"

          # Restart celery workers and beat
          docker-compose restart celery_worker celery_beat

          # Restart nginx
          sudo service nginx restart

          # Sleep for 10 seconds
          sleep 10

          # Clean up unused Docker images and build cache
          sudo docker image prune -a -f
          sudo docker builder prune -f

