name: Development Workflow

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/www/surrat_backend


            git reset --hard
            git pull origin development
            docker-compose up --build -d


            docker-compose exec surrat_backend python manage.py makemigrations
            docker-compose exec surrat_backend python manage.py migrate
            docker-compose restart celery_worker celery_beat
